# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 3.9.3"

#Github Pages
#gem "github-pages", group: jekyll_plugins

#Theme: Minimal Mistakes
gem "minimal-mistakes-jekyll", "~> 4.26"

group :jekyll_plugins do
    gem "jekyll-include-cache"
    gem "github-pages"
    gem "jekyll-feed"
    gem "jekyll-seo-tag"
    gem "webrick"
end
